spring:
  mail:
    host: smtp.gmail.com
    username: pkumar.c028@gmail.com
    port: '587'
    properties:
      mail:
        smtp:
          starttls:
            enable: 'true'
          auth: 'true'
    password: pvqf ggit xvyn gepu
  application:
    name: QuizzPro_Prasanna
  datasource:
    password: kumar123
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      idle-timeout: '2000000'
      maximum-pool-size: '10'
    username: root
    url: jdbc:mysql://localhost:3306/quizzdb
  mvc:
    view:
      prefix: /WEB-INF/myjsps/
      suffix: .jsp
  banner:
    location: classpath:banner.txt
logging:
  pattern:
    console: '%-5level %logger{36} -%m%n'
  level:
    root: 'info          '
server:
  port: '12345'
