spring:
  mail:
    host: smtp.gmail.com
    username: pkumar.c028@gmail.com
    port: '587'
    properties:
      mail:
        smtp:
          starttls:
            enable: 'true'
          auth: 'true'
    password: pvqf ggit xvyn gepu
  application:
    name: QuizzPro_Prasanna
  datasource:
    hikari:
      idle-timeout: '2000000'
      maximum-pool-size: '10'
  mvc:
    view:
      prefix: /WEB-INF/myjsps/
      suffix: .jsp
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  banner:
    location: classpath:banner.txt
  profiles:
    active:
    - "dev"
logging:
  pattern:
    console: '%-5level %logger{36} -%m%n'
  level:
    root: 'info          '
server:
  port: '12345'


