################################
#Spring mail
################################
spring:
  mail:
    properties:
      mail:
        smtp:
          starttls:
            enable: 'true'
          auth: 'true'
    host: smtp.gmail.com
    username: pkumar.c028@gmail.com
    password: pvqf ggit xvyn gepu
    port: '587'
################################
#Spring mail
################################
  application:
    name: QuizzPro_Prasanna
################################
#Spring DataSource
################################	
  datasource:
    hikari:
      idle-timeout: 2000000
      maximum-pool-size: 10
################################
#Spring MVC
################################  
  mvc:
    view:
      prefix: /WEB-INF/myjsps/
      suffix: .jsp
################################
#Swagger
################################	
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
################################
#Logger
################################
logging:
  pattern:
    console: '%-5level %logger{36} -%m%n'
  level:
    root: 'info'   
################################
#Server Port
################################
server:
  port: 12345
################################
